Backward Propagation

In [53]:
import numpy as np

In [54]:
from numpy import array
from keras.activations import sigmoid
from keras.losses import mse

In [55]:
inputSize=2
outputSize=1
hiddenSize=3

W1=np.random.randn(inputSize, hiddenSize)
W2=np.random.randn(hiddenSize, outputSize)

In [56]:
W1

array([[-0.79415273,  0.71501696, -0.28758262],
       [-0.67050468,  0.99828321, -0.51794653]])

In [57]:
W2

array([[-1.89522948],
       [-0.44707443],
       [ 0.84051955]])

In [58]:
y_true=np.array([0.3428])
y_pred=np.array([0.909])

In [59]:
#k=mse(y_true,y_pred).numpy()
#k

In [60]:
output_error=y_pred-y_true
output_error

array([0.5662])

In [61]:
output_delta=output_error*(y_true*(1-y_true))
output_delta

array([0.12755816])