In [82]:
import numpy as np

In [83]:
from numpy import array

Error Computation

In [84]:
y_true=np.array([0.3428])
y_pred=np.array([0.909])

In [85]:
output_error=y_pred-y_true
output_delta=output_error*(y_true*(1-y_true))
output_delta

array([0.12755816])

Back Propagation

In [86]:
output_j=np.array([0.5788])
delta_j=output_j*(1-output_j)
error_j=output_delta*([0.5])*delta_j
error_j

array([0.01554874])

In [87]:
output_i=np.array([0.534])
delta_i=output_i*(1-output_i)
error_i=output_delta*([0.5])*delta_i
error_i

array([0.01587104])

Weight Updates