In [123]:
import numpy as np

In [124]:
from numpy import array

In [125]:
y_true=np.array([0.3428])
y_pred=np.array([0.909])

Error Computation

In [126]:
output_error=y_pred-y_true
output_delta=output_error*(y_true*(1-y_true))
output_delta

array([0.12755816])

Back Propagation

In [127]:
wjk=0.5
output_j=0.5788
delta_j=output_j*(1-output_j)
error_j=output_delta*wjk*delta_j
error_j

array([0.01554874])

In [128]:
wik=0.1
output_i=0.534
delta_i=output_i*(1-output_i)
error_i=output_delta*wik*delta_i
error_i

array([0.00317421])

Weight Updates

In [129]:
n=0.03  #learning rate
current_w=n*output_delta*y_true
new_wjk=wjk+current_w
new_wjk


array([0.50131181])

In [130]:
new_wik=wik+current_w
new_wik

array([0.10131181])