In [1]:
import pandas as pd 
import numpy as np

In [2]:
from numpy import array
from sklearn.preprocessing import Normalizer
from keras.activations import sigmoid
from keras.losses import mse
from numpy.random import uniform

Hyperparameters

In [3]:
batch_size=2

Dataset

In [4]:
data={'Day 1':[30,40,50,20,15,60],'Day 2':[40,50,20,15,60,70],
      'Day 3':[50,20,15,60,70,50],'Target':[20,15,60,70,50,40]}

In [5]:
dataset=pd.DataFrame(data)

In [6]:
dataset

Day 1  Day 2  Day 3  Target
0     30     40     50      20
1     40     50     20      15
2     50     20     15      60
3     20     15     60      70
4     15     60     70      50
5     60     70     50      40

In [7]:
X=dataset.drop('Target',axis=1)
y=dataset['Target']

In [8]:
X

Day 1  Day 2  Day 3
0     30     40     50
1     40     50     20
2     50     20     15
3     20     15     60
4     15     60     70
5     60     70     50

In [9]:
X_norm = Normalizer(norm='max').fit_transform(X)

In [10]:
X_norm

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

In [11]:
array(y)

array([20, 15, 60, 70, 50, 40])

In [12]:
np.reshape(array(y),(1,-1))

array([[20, 15, 60, 70, 50, 40]])

In [13]:
y_norm=Normalizer(norm='max').fit_transform(np.reshape(array(y),(1,-1)))

In [14]:
y_norm

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

ANN From Scratch

In [15]:
"""weight_1=array([[.2,.1],[.3,.1],[.2,.1]])
weight_2=array([[.5],[.1]])"""

'weight_1=array([[.2,.1],[.3,.1],[.2,.1]])\nweight_2=array([[.5],[.1]])'

In [16]:
weight_1=uniform(-1,1,(3,2)) #shape 3 by 2
weight_2=uniform(-1,1,(2,1))

In [17]:
weight_1

array([[-0.44639868, -0.12329145],
       [-0.07976392,  0.23312722],
       [ 0.00392791, -0.07453559]])

In [18]:
X_norm[0:batch_size]

array([[0.6, 0.8, 1. ],
       [0.8, 1. , 0.4]])

In [19]:
output_1=X_norm[0:batch_size]@weight_1
output_1

array([[-0.32772243,  0.03799132],
       [-0.4353117 ,  0.10467983]])

In [20]:
act_output=sigmoid(output_1).numpy()
act_output

array([[0.41879489, 0.50949669],
       [0.39285866, 0.52614609]])

In [33]:
pred_output=act_output@weight_2
pred_output=np.reshape(pred_output,(1,-1))

Mean Squared Error

In [35]:
y_true=y_norm[0][0:batch_size]
y_pred=pred_output

In [23]:
y_true

array([0.28571429, 0.21428571])

In [36]:
mse(y_true,y_pred).numpy()

array([0.17259981])